### ISSUE TITLE
ext-mongodb is missing from the akeneo images

### ISSUE THREAD

**Issue by Erwyn** [akeneo/Dockerfiles#122] opened 2017-01-19 14:16 UTC
Hello,

I'm trying to use the docker-compose files to have a dev environment for Akeneo. I may have gotten something wrong, but at least the apache version, when running the `docker-compose exec akeneo php -d memory_limit=-1 /usr/local/bin/composer update` I get a missing `ext-mongodb` dependency for the system. I have this with `akeneo:php-5.6` as well as `latest`.

Here is the complete stacktrace:

```
Problem 1
    - alcaeus/mongo-php-adapter 1.0.0 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.1 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.2 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.3 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.4 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.5 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.6 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.7 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - alcaeus/mongo-php-adapter 1.0.8 requires mongodb/mongodb ^1.0.1 -> satisfiable by mongodb/mongodb[1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.1.0, 1.1.1].
    - mongodb/mongodb 1.1.1 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.1.0 requires ext-mongodb ^1.2.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.4 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.3 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.2 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - mongodb/mongodb 1.0.1 requires ext-mongodb ^1.1.0 -> the requested PHP extension mongodb is missing from your system.
    - Installation request for alcaeus/mongo-php-adapter ^1.0 -> satisfiable by alcaeus/mongo-php-adapter[1.0.0, 1.0.1, 1.0.2, 1.0.3, 1.0.4, 1.0.5, 1.0.6, 1.0.7, 1.0.8].

  To enable extensions, verify that they are enabled in your .ini files:
    - /etc/php5/cli/php.ini
    - /etc/php5/cli/conf.d/05-opcache.ini
    - /etc/php5/cli/conf.d/10-pdo.ini
    - /etc/php5/cli/conf.d/20-apcu.ini
    - /etc/php5/cli/conf.d/20-curl.ini
    - /etc/php5/cli/conf.d/20-gd.ini
    - /etc/php5/cli/conf.d/20-imagick.ini
    - /etc/php5/cli/conf.d/20-intl.ini
    - /etc/php5/cli/conf.d/20-json.ini
    - /etc/php5/cli/conf.d/20-mcrypt.ini
    - /etc/php5/cli/conf.d/20-mongo.ini
    - /etc/php5/cli/conf.d/20-mysql.ini
    - /etc/php5/cli/conf.d/20-mysqli.ini
    - /etc/php5/cli/conf.d/20-pdo_mysql.ini
  You can also run `php --ini` inside terminal to see which files are used by PHP in CLI mode.
```

**Comment by damien-carcel** [comment] 2017-01-19 15:01
Hello @Erwyn.

No, you didn't miss anything, it is my fault. I forgot an important element in the documentation: on PHP 7.x, you need to run composer with the option `--ignore-platform-reqs` or you end with the error you report. It is caused by Doctrine mongodb bundle, which looks only for the old `mongod` extension (the one for PHP 5.x) and not for the new one.

So after adding `alcaeus/mongo-php-adapter`, the right command is:
`docker-compose exec akeneo php -d memory_limit=-1 /usr/local/bin/composer --ignore-platform-reqs update `.

I will amend the `COMPOSE.md` as soon as possible. Thank you for reporting this issue :+1: .

Damien.

**Comment by Erwyn** [comment] 2017-01-19 15:13
I must add that this issue exists as well for `php-5.6`. I had to install the `php-pear` package as long as openssl libraries to install the mongodb extension through `pecl install mongodb`.

Should I run with the `--ignore-platform-reqs` as well for `php-5.6`?

**Comment by damien-carcel** [comment] 2017-01-19 15:23
Nope, this is not needed for PHP 5.6, and the images come with `php5-mongo`, so you should not have to use pecl at all.

That is strange. I am sure mongo works fine on the PHP 5.6 images as I use them on a daily basis. And you don't need `alcaeus/mongo-php-adapter` with PHP 5.6.

I think I must organize the documentation differently, as in fact the content is not the same depending of the branch you are on (for instance, I don't mention `alcaeus/mongo-php-adapter` on the php-5.6 branch).

**Comment by Erwyn** [comment] 2017-01-19 15:39
Oh, I see, I understand now, I'll try with the 5.6 branch.

**Comment by Erwyn** [comment] 2017-01-19 16:29
Okay, so I confirm now, this is not a problem with the 5.6 branch.

**Comment by jmleroux** [comment] 2017-02-22 23:20
should be closed

**Comment by damien-carcel** [comment] 2017-02-23 12:02
As the issue has been fixed by the documentation and is now one month old, I am closing it.

**Closed as completed by damien-carcel** 2017-02-23 12:02 UTC
Labels: question
