### ISSUE TITLE
ERROR: for nginx  Cannot start service nginx: oci runtime error

### ISSUE THREAD

**Issue by nidup** [akeneo/Dockerfiles#251] opened 2017-06-19 12:39 UTC
| Q                      | A
| ---------------------- | -----
| Bug report?            | yes
| Feature request?       | no
| BC Break report?       | no
| RFC?                   | no
| Affected image and tag | -

When doing the first docker-compose up -d with this configuration https://github.com/damien-carcel/Dockerfiles/blob/master/Docs/akeneo/docker-compose.yml.fpm_dist

I got the following error msg,

```
ERROR: for nginx  Cannot start service nginx: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/home/nico/git/pim-ee-18/docker/nginx.conf\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/b8ad0fe0119bab91b46fdc4d408b5b9de7ca2f970cd5ed0e9dea512258d5f9bb\\\" at \\\"/var/lib/docker/aufs/mnt/b8ad0fe0119bab91b46fdc4d408b5b9de7ca2f970cd5ed0e9dea512258d5f9bb/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

ERROR: for nginx-behat  Cannot start service nginx-behat: oci runtime error: container_linux.go:247: starting container process caused "process_linux.go:359: container init caused \"rootfs_linux.go:54: mounting \\\"/home/nico/git/pim-ee-18/docker/nginx-behat.conf\\\" to rootfs \\\"/var/lib/docker/aufs/mnt/931beb8cfcd2672ebbab5731c733517f4c05cf3d3f2fbb57f7e7961c2992c947\\\" at \\\"/var/lib/docker/aufs/mnt/931beb8cfcd2672ebbab5731c733517f4c05cf3d3f2fbb57f7e7961c2992c947/etc/nginx/conf.d/default.conf\\\" caused \\\"not a directory\\\"\""
: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type
ERROR: Encountered errors while bringing up the project.
```

**Comment by damien-carcel** [comment] 2017-06-19 17:40
Hello @nidup.

Thank you for raising this issue. It allowed me to see two mistakes: the `node` service in the FPM compose file is too much indented, and I forgot to remove `oro:requirejs:generate-config` from the scipts of `carcel/akeneo-fpm:php-7.1). This is fixed by this in [this PR](https://github.com/damien-carcel/Dockerfiles/pull/253/commits/929ae91987d91a4a69d158803ec029ff1a518054) and [this one](https://github.com/damien-carcel/Dockerfiles/pull/252), respectively.

However, this indentation issue seems not the cause of your problem, and I am unable to reproduce it on my machine. According to [this issue](https://github.com/docker/compose/issues/424#issuecomment-280721396), it could be caused by an outdated Docker installation.

Also, do not forget that updating Docker do probably not update compose, as on Debian it is a script you install separately.

I am myself using Docker 17.05 and Compose 1.13.0. Let me know if this helps.

Regards,
Damien.

**Comment by damien-carcel** [comment] 2017-06-26 16:18
@nidup Any news on this one? 😉 
I think the problem was you didn't create the configuration files for nginx in the `docker` subfolder of your project. Let me know if it is the case.

Cheers,
Damien

**Comment by damien-carcel** [comment] 2017-08-31 11:45
As `master` branch of the PIM introduced its own compose file, with Apache 2.4 (with FCGI preconfigured) and FPM, I consider this issue as closed.

**Closed as completed by damien-carcel** 2017-08-31 11:45 UTC
Labels: bug, documentation

**Comment by tavurth** [comment] 2018-03-15 19:57
This fixed my issue. I had a sym-link from my `nginx.dist.conf` to my `nginx.conf` and the link had gotten messed up in git. Deleting the link and recreating solved the issue.
